### ISSUE TITLE
文章【CPU 性能和Cache Line】链接掉了

### ISSUE THREAD

**Issue by Lauamoe** [plantegg/plantegg.github.io#2]
文章【CPU 性能和Cache Line】链接掉了，无法访问。
![image](https://github.com/plantegg/plantegg.github.io/assets/117897774/e5c379f7-4d09-4ce0-845b-26b1a027e205)

**Comment by plantegg** [comment]
这个：https://plantegg.github.io/2021/05/16/CPU_Cache_Line%E5%92%8C%E6%80%A7%E8%83%BD/
或者直接到CPU 专栏下：https://plantegg.github.io/categories/CPU/
